### ISSUE TITLE
Add the RetDec decompiler plugin

### ISSUE THREAD

**Issue by ITAYC0HEN** [radareorg/cutter-plugins#11]
**Description**

Avast released their integration of the RetDec decompiler inside Cutter and Radare2. Add this to the list of plugins

https://github.com/avast/retdec-r2plugin

**Comment by julianxhokaxhiu** [comment]
I just came here as I'm the original author of an issue over there ( https://github.com/avast/retdec-r2plugin/issues/14 ) which is about releasing a Cutter plugin.

Now in the readme over here I read maintained, although it's confusing on who is going to release the plugin. As I see in their official page, it seems that the plugin has to be compiled manually, although this reduces the adoption for RetDec tremendously.

Is there an intention to include the RetDec plugin inside of Cutter OOB or is this on their side to release the artifacts ( at least for Windows )?

**Comment by karliss** [comment]
There are multiple reasons why making official retdec packages is somewhat problematic. It might get easier after some of the packaging refactoring I am working on 
 in https://github.com/radareorg/cutter/issues/2098 .
* Symbol exporting for windows needs to be fixed. At the moment r2hidra plugin gets handled in a hacky way by static linking it inside Cutter.
* Size during build and after the build. Artifacts in  retdec-r2plugin repo are ~1.2GB. Cutter release is currently 60-100MB. Ensuring that Cutter release packages contains all the files for easily compiling plugins against it would make it easier to build retdec separately against release packages. 
* From what I understand retdec uses LLVM. There used to be a problem with GUI software linking against LLVM that doesn't match system one because some of linux GPU drivers also use LLVM. And having 2 of them was causing conflict. Not sure if this problem has been resolved.

**Comment by julianxhokaxhiu** [comment]
Talking with the avast authors I think they will manage to pack some artifacts. So this should not be an issue on your side :)

But also looking at your reply it look clear to me that it would add too much overhead on your side, this means it makes sense to keep it on theirs.

Still I would like to thank you for your time and the reply. Is really appreciated!
